### ISSUE TITLE
How to installed Abaqus2matlab in ubuntu

### ISSUE THREAD

**Issue by SubChange** [GeorgePapazafeiropoulos/Abaqus2Matlab#1]
Is there any way to install this software in ubuntu 18.04

**Comment by GeorgePapazafeiropoulos** [comment]
Hello,
Abaqus2Matlab application is supposed to be installable in Matlab software for Ubuntu OS in the same way as it is for Windows OS. However, if you get errors during the installation, please consult the following links:

https://www.mathworks.com/matlabcentral/answers/458061-error-installing-app-mlappinstall

https://www.mathworks.com/matlabcentral/answers/293235-how-do-i-download-and-install-a-support-package-on-an-offline-machine

https://www.mathworks.com/matlabcentral/answers/121434-how-to-download-a-support-package-for-installation-on-a-offline-computer-for-matlab-r2016a-and-below

Best regards,
George Papazafeiropoulos
